framework:
    messenger:
        transports:
            messages: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                options:
                    exchange:
                        name: amqp
                    queues:
                        messages: ~

        routing:
            # Messages are routed via #[AsMessage('messages')] attribute on message classes
