services:

  front:
    image: node:20-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_front
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:5173"
    volumes:
      - ./front:/app
    environment:
      - VITE_API_URL=${API_URL}
      - VITE_SENTRY_DSN=${SENTRY_DSN_FRONT}
      - VITE_PRELAUNCH_ENABLED=${PRELAUNCH_ENABLED}
      - VITE_PUBLIC_POSTHOG_PROJECT_TOKEN=${POSTHOG_PROJECT_TOKEN}
      - VITE_PUBLIC_POSTHOG_HOST=${POSTHOG_HOST}
    networks:
      - maker_flow
    depends_on:
      - back
    command: sh -c "npm ci && npm run dev"

  back:
    build:
      context: ./back
      dockerfile: .docker/build/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    container_name: ${COMPOSE_PROJECT_NAME}_back
    restart: unless-stopped
    volumes:
      - ./back:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_ENCRYPTION_KEY: ${APP_ENCRYPTION_KEY}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_HOST: ${MYSQL_DATABASE_HOST}
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      REDIS_STORE_HOST: ${REDIS_STORE_HOST}
      REDIS_STORE_PORT: ${REDIS_STORE_PORT}
      REDIS_STORE_SCHEME: ${REDIS_STORE_SCHEME}
      REDIS_STORE_PASSWORD: ${REDIS_STORE_PASSWORD}

      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/${RABBITMQ_VHOST}/messages

      INSTAGRAM_APP_ID: ${INSTAGRAM_APP_ID}
      INSTAGRAM_APP_SECRET: ${INSTAGRAM_APP_SECRET}
      INSTAGRAM_REDIRECT_URI: ${INSTAGRAM_REDIRECT_URI}
      FRONTEND_URL: ${FRONTEND_URL}

      YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID}
      YOUTUBE_PROJECT_ID: ${YOUTUBE_PROJECT_ID}
      YOUTUBE_AUTH_URI: ${YOUTUBE_AUTH_URI}
      YOUTUBE_TOKEN_URI: ${YOUTUBE_TOKEN_URI}
      YOUTUBE_AUTH_PROVIDER_X509_CERT_URL: ${YOUTUBE_AUTH_PROVIDER_X509_CERT_URL}
      YOUTUBE_CLIENT_SECRET: ${YOUTUBE_CLIENT_SECRET}
      YOUTUBE_REDIRECT_URI: ${YOUTUBE_REDIRECT_URI}
      YOUTUBE_JAVASCRIPT_ORIGIN: ${YOUTUBE_JAVASCRIPT_ORIGIN}

      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      SENTRY_DSN: ${SENTRY_DSN_BACK}

      RESEND_API_KEY: ${RESEND_API_KEY}
      MAILING_FROM_ADDRESS: ${MAILING_FROM_ADDRESS}
      MAILING_FROM_NAME: ${MAILING_FROM_NAME}

      PRELAUNCH_ENABLED: ${PRELAUNCH_ENABLED}
    ports:
      - "80:80"
    networks:
      - maker_flow
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - maker_flow_db_data:/var/lib/mysql
    networks:
      - maker_flow

  pma:
    image: arm64v8/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${PMA_MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - maker_flow
  
  redis-store:
    container_name: ${COMPOSE_PROJECT_NAME}_redis_store
    image: redis:8.4.0
    ports:
      - "6379:6379"
    networks:
      - maker_flow

  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - maker_flow_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - maker_flow
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  maker_flow_db_data:
  maker_flow_rabbitmq_data:

networks:
  maker_flow: