# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.domain: "%env(string:APP_DOMAIN)%"
    app.frontend_url: "%env(string:FRONTEND_URL)%"

    app.module.icon_path: "%kernel.project_dir%/private/uploads/module/icon"
    app.integration.provider.icon_path: "%kernel.project_dir%/private/uploads/integration/provider/icon"

    app.instagram.graph_url: "https://graph.instagram.com"
    app.instagram.authorization_url: "https://www.instagram.com/oauth/authorize"
    app.instagram.token_url: "https://api.instagram.com/oauth/access_token"

    app.instagram.app_id: "%env(string:INSTAGRAM_APP_ID)%"
    app.instagram.app_secret: "%env(string:INSTAGRAM_APP_SECRET)%"
    app.instagram.redirect_uri: "%env(string:INSTAGRAM_REDIRECT_URI)%"

    app.redis_store.scheme: "%env(string:REDIS_STORE_SCHEME)%"
    app.redis_store.host: "%env(string:REDIS_STORE_HOST)%"
    app.redis_store.port: "%env(string:REDIS_STORE_PORT)%"

    app.youtube.client_id: "%env(string:YOUTUBE_CLIENT_ID)%"
    app.youtube.project_id: "%env(string:YOUTUBE_PROJECT_ID)%"
    app.youtube.auth_uri: "%env(string:YOUTUBE_AUTH_URI)%"
    app.youtube.token_uri: "%env(string:YOUTUBE_TOKEN_URI)%"
    app.youtube.auth_provider_x509_cert_url: "%env(string:YOUTUBE_AUTH_PROVIDER_X509_CERT_URL)%"
    app.youtube.client_secret: "%env(string:YOUTUBE_CLIENT_SECRET)%"
    app.youtube.redirect_uri: "%env(string:YOUTUBE_REDIRECT_URI)%"
    app.youtube.javascript_origin: "%env(string:YOUTUBE_JAVASCRIPT_ORIGIN)%"
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    ### Normalizers ###
    App\Serializer\UserTimezoneDateTimeNormalizer:
        arguments:
            $dateTimeNormalizer: '@serializer.normalizer.datetime'
        tags: ['serializer.normalizer']

    App\Service\Cookie\CookieService:
        arguments:
            $appDomain: "%app.domain%"
    App\Service\Module\ModuleService:
        arguments:
            $moduleIconPath: "%app.module.icon_path%"
    App\Service\RedisStore\RedisStoreService:
        arguments:
            $scheme: "%app.redis_store.scheme%"
            $host: "%app.redis_store.host%"
            $port: "%app.redis_store.port%"

    App\Service\Integration\InstagramOAuthService:
        arguments:
            $instagramGraphUrl: "%app.instagram.graph_url%"
            $instagramAuthorizationUrl: "%app.instagram.authorization_url%"
            $instagramTokenUrl: "%app.instagram.token_url%"
            $instagramAppId: "%app.instagram.app_id%"
            $instagramAppSecret: "%app.instagram.app_secret%"
            $instagramRedirectUri: "%app.instagram.redirect_uri%"

    Google\Client:
        autowire: false

    App\Service\Integration\YoutubeOAuthService:
        arguments:
            $youtubeClientId: "%app.youtube.client_id%"
            $youtubeProjectId: "%app.youtube.project_id%"
            $youtubeAuthUri: "%app.youtube.auth_uri%"
            $youtubeTokenUri: "%app.youtube.token_uri%"
            $youtubeAuthProviderX509CertUrl: "%app.youtube.auth_provider_x509_cert_url%"
            $youtubeClientSecret: "%app.youtube.client_secret%"
            $youtubeRedirectUri: "%app.youtube.redirect_uri%"
            $youtubeJavascriptOrigin: "%app.youtube.javascript_origin%"

    App\Controller\IntegrationController:
        arguments:
            $frontendUrl: "%app.frontend_url%"
    App\Service\Integration\IntegrationService:
        arguments:
            $integrationProviderIconPath: "%app.integration.provider.icon_path%"
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
